apiVersion: v1
kind: Service
metadata:
  name: sample-api
  labels:
    app: service
spec:
  ports:
    - port: 5678
  selector:
    app: service
    tier: sample-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  labels:
    app: service
spec:
  selector:
    matchLabels:
      app: service
      tier: sample-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service
        tier: sample-api
    spec:
      containers:
      - image: cloudeyes/sample-service
        name: sample-api
        env:
        - name: ENV
          value: PROD
        - name: DB_HOST
          value: mysql.sample.svc.cluster.local
        - name: DB_TYPE
          value: mysql
        - name: DB_NAME
          value: sample
        - name: DB_USER
          value: sample
        - name: DB_PASS
          value: sample
        ports:
        - containerPort: 5678
          name: sample-api
